-- MySQL Script generated by MySQL Workbench
-- Sun Jan  7 16:47:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema running_business
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema running_business
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `running_business` DEFAULT CHARACTER SET utf8 ;
USE `running_business` ;

-- -----------------------------------------------------
-- Table `running_business`.`run_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_user` (
  `uid` INT NOT NULL AUTO_INCREMENT COMMENT '用户id',
  `userphone` VARCHAR(45) NOT NULL COMMENT '用户账号(手机号)',
  `password` VARCHAR(45) NOT NULL COMMENT '用户密码',
  `add_time` DATETIME NOT NULL COMMENT '添加时间',
  `update_time` DATETIME NOT NULL COMMENT '更新时间',
  `user_status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '用户状态0:不在线，1:在线',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除 0:没删，1:已删',
  UNIQUE INDEX `uusername_UNIQUE` (`userphone` ASC),
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_user_info` (
  `uid` INT NOT NULL COMMENT '用户id',
  `user_photo` VARCHAR(100) NULL COMMENT '头像地址',
  `user_name` VARCHAR(45) NULL COMMENT '用户姓名',
  `user_gender` TINYINT(1) NULL DEFAULT 1 COMMENT '用户性别：1:男，0:女',
  `user_phone` VARCHAR(45) NOT NULL COMMENT '用户电话',
  `user_point` INT NULL DEFAULT 0 COMMENT '用户积分',
  `user_address_id` INT NULL COMMENT '当前地址id',
  `reported_times` INT NULL DEFAULT 0 COMMENT '被举报次数',
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_user_balance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_user_balance` (
  `uid` INT NOT NULL COMMENT '用户id',
  `user_balance` DOUBLE NOT NULL DEFAULT 0 COMMENT '用户余额',
  `update_time` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_user_coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_user_coupon` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '优惠卷id',
  `uid` INT NOT NULL COMMENT '用户id',
  `title` VARCHAR(45) NULL COMMENT '标题',
  `content` VARCHAR(1000) NULL COMMENT '内容',
  `type` VARCHAR(45) NULL COMMENT '类型',
  `full` DOUBLE NULL COMMENT '满额',
  `subtract` DOUBLE NULL COMMENT '减额',
  `status` INT NOT NULL DEFAULT 0 COMMENT '状态 0:可用，1:不可用',
  `begin_time` DATETIME NULL COMMENT '开始时间',
  `expired_time` DATETIME NULL COMMENT '过期时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_user_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_user_address` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '地址id',
  `uid` INT NOT NULL COMMENT '用户id',
  `user_address` VARCHAR(100) NOT NULL COMMENT '地址',
  `longitude` VARCHAR(45) NOT NULL COMMENT '经度',
  `latitude` VARCHAR(45) NOT NULL COMMENT '纬度',
  `add_time` DATETIME NOT NULL COMMENT '创建时间',
  `update_time` DATETIME NOT NULL COMMENT '更新时间',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_user_balance_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_user_balance_record` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '用户交易记录id',
  `uid` INT NOT NULL COMMENT '用户id',
  `old_balance` DOUBLE NOT NULL COMMENT '老余额',
  `amount` DOUBLE NOT NULL COMMENT '修改金额',
  `new_balance` DOUBLE NOT NULL COMMENT '新余额',
  `type` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '交易类型 0:入款，1:出款',
  `number` VARCHAR(45) NOT NULL COMMENT '交易流水号',
  `add_time` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_user_preference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_user_preference` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '用户偏好id',
  `uid` INT NOT NULL COMMENT '用户id',
  `user_goodstype` VARCHAR(45) NULL COMMENT '喜好类型',
  `user_goods` VARCHAR(45) NULL COMMENT '喜好物品',
  `times` INT NOT NULL DEFAULT 0 COMMENT '购买次数',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_deliveryuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_deliveryuser` (
  `did` INT NOT NULL COMMENT '配送员id',
  `userphone` VARCHAR(45) NOT NULL COMMENT '账号',
  `password` VARCHAR(45) NOT NULL COMMENT '密码',
  `add_time` DATETIME NOT NULL COMMENT '创建时间',
  `update_time` DATETIME NOT NULL COMMENT '更新时间',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '状态0:在线，1:不在线',
  `available` TINYINT(1) NULL DEFAULT 1 COMMENT '0:启用，1:禁用',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `credits` INT NULL DEFAULT 100 COMMENT '信用额度',
  `review_photo` VARCHAR(45) NULL COMMENT '审核照片',
  PRIMARY KEY (`did`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_delivery_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_delivery_info` (
  `did` INT NOT NULL COMMENT '配送员id',
  `photo` VARCHAR(100) NULL COMMENT '头像',
  `name` VARCHAR(45) NOT NULL COMMENT '姓名',
  `card` VARCHAR(45) NOT NULL COMMENT '身份证',
  `gender` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '性别 0:女，1:男',
  `phone` VARCHAR(45) NOT NULL COMMENT '电话',
  `address_id` INT NULL COMMENT '地址id',
  `point` INT NULL DEFAULT 0 COMMENT '积分',
  `level` VARCHAR(45) NULL COMMENT '水平，称号',
  `reported_times` INT NULL DEFAULT 0 COMMENT '被举报次数',
  PRIMARY KEY (`did`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_delivery_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_delivery_address` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '配送员地址id',
  `did` INT NOT NULL COMMENT '配送员id',
  `delivery_address` VARCHAR(45) NOT NULL COMMENT '配送员地址',
  `longitude` VARCHAR(45) NOT NULL COMMENT '经度',
  `latitude` VARCHAR(45) NOT NULL COMMENT '纬度',
  `add_time` DATETIME NOT NULL COMMENT '创建时间',
  `update_time` DATETIME NOT NULL COMMENT '更新时间',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_delivery_balance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_delivery_balance` (
  `did` INT NOT NULL COMMENT '配送员id',
  `delivery_balance` DOUBLE NOT NULL DEFAULT 0 COMMENT '配送员余额',
  `update_time` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`did`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_delivery_balance_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_delivery_balance_record` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '配送员交易流水号',
  `did` INT NOT NULL COMMENT '配送员id',
  `old_balance` DOUBLE NOT NULL COMMENT '老余额',
  `amount` DOUBLE NOT NULL COMMENT '修改金额',
  `new_balance` DOUBLE NOT NULL COMMENT '新余额',
  `type` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '交易类型0:入款，1:出款',
  `number` VARCHAR(45) NOT NULL COMMENT '交易流水号',
  `add_time` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_order` (
  `orderid` VARCHAR(45) NOT NULL COMMENT '订单号',
  `uid` INT NOT NULL COMMENT '用户id',
  `did` INT NULL COMMENT '配送员id',
  `type` INT NOT NULL DEFAULT 0 COMMENT '订单类型：0：帮我买，1:帮我送，2:帮我取，3:代排队',
  `goods` VARCHAR(45) NULL COMMENT '购买物品',
  `source_address` VARCHAR(45) NULL COMMENT '源地址：0:收货地址，1:发货地址，2:取货地址，3:排队地址',
  `source_remark_address` VARCHAR(100) NULL COMMENT '源备注地址：0:收货地址，1:发货地址，2:取货地址，3:排队地址',
  `source_phone` VARCHAR(45) NULL COMMENT '源电话：0:收货电话，1:发货电话，2:取货电话，3:排队电话',
  `target_address` VARCHAR(45) NULL COMMENT '目标地址：0:购买地址，1:收货地址，2:收货地址，3:排队地址',
  `target_remark_address` VARCHAR(100) NULL COMMENT '目标备注地址：0:购买地址，1:收货地址，2:收货地址，3:排队地址',
  `target_phone` VARCHAR(45) NULL COMMENT '目标电话：0:购买电话，1:收货电话，2:收货电话，3:排队电话',
  `remark` VARCHAR(100) NULL COMMENT '购买要求／备注信息',
  `require_time` DATETIME NULL COMMENT '送货时间／发货时间／取货时间／排队时间',
  `time_long` BIGINT NULL COMMENT '尽快送达／所需时常（秒或毫秒）',
  `amount` DOUBLE NOT NULL DEFAULT 0 COMMENT '跑腿费',
  `fee` DOUBLE NULL DEFAULT 0 COMMENT '小费',
  `distance` DOUBLE NULL COMMENT '订单距离',
  `source_longitude` VARCHAR(45) NULL COMMENT '源地址经度',
  `source_latitude` VARCHAR(45) NULL COMMENT '源地址纬度',
  `recv_longitude` VARCHAR(45) NULL COMMENT '收货地址经度',
  `recv_latitude` VARCHAR(45) NULL COMMENT '收货地址纬度',
  `status` INT NULL COMMENT '订单状态：0:已下单，1:已支付，2:已接单，3:已到达目的地，4:已完成，5:已退款',
  `pay_type` INT NOT NULL DEFAULT 0 COMMENT '支付类型：0:到付，1: 在线',
  `pay_amout` DOUBLE NULL COMMENT '到付金额',
  `add_time` DATETIME NOT NULL COMMENT '创建时间',
  `update_time` DATETIME NOT NULL COMMENT '修改时间',
  `recv_time` DATETIME NULL COMMENT '接单时间',
  `target_time` VARCHAR(45) NULL COMMENT '到达目的地时间',
  `finish_time` DATETIME NULL COMMENT '订单完成时间',
  PRIMARY KEY (`orderid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_order_status` (
  `orderid` VARCHAR(45) NOT NULL COMMENT '已废弃表',
  `uid` INT NOT NULL,
  `did` INT NULL,
  `order_is_submit` INT NULL DEFAULT 0,
  `order_is_pay` INT NULL DEFAULT 0,
  `order_is_orders` INT NULL DEFAULT 0,
  `order_is_send` INT NULL DEFAULT 0,
  `order_is_finish` INT NULL DEFAULT 0,
  `order_orders_time` DATETIME NULL,
  `order_finish_time` DATETIME NULL,
  PRIMARY KEY (`orderid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_order_pay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_order_pay` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '用户支付订单记录',
  `uid` INT NOT NULL COMMENT '用户id',
  `orderid` VARCHAR(45) NOT NULL COMMENT '订单号',
  `order_price` DOUBLE NOT NULL COMMENT '订单价格',
  `pay_amount` DOUBLE NULL COMMENT '在线付款金额',
  `order_tip` DOUBLE NULL COMMENT '小费',
  `order_subtract` DOUBLE NULL COMMENT '减额',
  `order_actual_price` DOUBLE NULL COMMENT '实际付款金额=订单金额+在线金额+小费-满减',
  `pay_type` INT NOT NULL DEFAULT 0 COMMENT '支付类型：0:到付，1：余额，2:支付宝，3:微信，4:银行卡 等等',
  `pay_time` DATETIME NOT NULL COMMENT '支付时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_delivery_distance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_delivery_distance` (
  `did` INT NOT NULL COMMENT '配送员id',
  `send_distance` DOUBLE NOT NULL DEFAULT -1 COMMENT '从源地址到目标地址的距离长度（配送员可选择最大配送长度）',
  `delivery_distance` DOUBLE NOT NULL DEFAULT -1 COMMENT '可配送距离范围（里或公里都可）',
  `view_order_distance` DOUBLE NOT NULL DEFAULT -1 COMMENT '抢单时显示的订单到配送员的距离（为了抢单调度）',
  `update_time` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`did`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_push_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_push_info` (
  `pid` INT NOT NULL AUTO_INCREMENT COMMENT '推送信息id',
  `operator` INT NULL COMMENT '操作人id',
  `push_title` VARCHAR(100) NULL COMMENT '推送标题',
  `push_content` TEXT NULL COMMENT '推送内容',
  `push_photo` VARCHAR(100) NULL COMMENT '推送图片',
  `push_status` INT NOT NULL DEFAULT 0 COMMENT '推送状态 0:未推送，1:已推送',
  `push_time` DATETIME NULL COMMENT '推送时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除 0:不删除，1:已删除',
  PRIMARY KEY (`pid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_info` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '轮播消息id',
  `content` VARCHAR(100) NULL COMMENT '轮播消息内容',
  `info_time` DATETIME NULL COMMENT '消息时间',
  `add_time` DATETIME NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_admin` (
  `admin_id` INT NOT NULL AUTO_INCREMENT COMMENT '管理员id',
  `admin_username` VARCHAR(45) NOT NULL COMMENT '账号',
  `admin_password` VARCHAR(45) NOT NULL COMMENT '密码',
  `admin_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`run_admin_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`run_admin_info` (
  `admin_id` INT NOT NULL COMMENT '管理员id',
  `admin_name` VARCHAR(45) NULL COMMENT '姓名',
  `admin_phone` VARCHAR(45) NULL COMMENT '电话',
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`refund_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`refund_record` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '退款记录id',
  `uid` INT NOT NULL COMMENT '用户id',
  `did` INT NULL COMMENT '配送员id',
  `orderid` VARCHAR(45) NOT NULL COMMENT '订单id',
  `amount` DOUBLE NOT NULL DEFAULT 0 COMMENT '退款金额',
  `reason` VARCHAR(200) NULL COMMENT '退款理由',
  `responsibility` INT NOT NULL DEFAULT 0 COMMENT '责任方0:用户，1:配送员，2:系统，3:第三方',
  `source` INT NOT NULL DEFAULT 0 COMMENT '来源 0：余额，1:支付宝，2:微信，3:银行卡，等等',
  `operator` INT NOT NULL COMMENT '操作者',
  `add_time` DATETIME NULL COMMENT '退款时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`refund_apply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`refund_apply` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '退款申请id',
  `uid` INT NOT NULL COMMENT '用户id',
  `orderid` VARCHAR(45) NOT NULL COMMENT '订单id',
  `amount` DOUBLE NULL COMMENT '退款金额',
  `reason` VARCHAR(200) NULL COMMENT '申请理由',
  `status` INT NULL COMMENT '申请状态：0：正在审核，1:审核通过，2:审核不通过',
  `operator` INT NULL,
  `add_time` DATETIME NULL COMMENT '申请时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `running_business`.`report_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `running_business`.`report_record` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '举报记录id',
  `uid` INT NOT NULL,
  `did` INT NOT NULL,
  `active_side` INT NOT NULL DEFAULT 0 COMMENT '主动举报方 0:用户，1:配送员',
  `reason` VARCHAR(200) NOT NULL COMMENT '理由',
  `level` INT NULL DEFAULT 0 COMMENT '举报等级 0:有瑕疵，1:比较过分，2:过分，3:很过分，4：超级过分，5：杀千刀的',
  `add_time` DATETIME NULL COMMENT '举报时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
