-- MySQL Script generated by MySQL Workbench
-- Wed Oct 25 23:11:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Running_Bussiness
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Running_Bussiness
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Running_Bussiness` DEFAULT CHARACTER SET utf8 ;
USE `Running_Bussiness` ;

-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_user` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `user_username` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  `user_date` DATETIME NOT NULL,
  UNIQUE INDEX `uusername_UNIQUE` (`user_username` ASC),
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_user_info` (
  `uid` INT NOT NULL,
  `user_photo` VARCHAR(100) NULL,
  `user_name` VARCHAR(45) NULL,
  `user_gender` INT NULL DEFAULT 0,
  `user_phone` VARCHAR(45) NOT NULL,
  `user_point` INT NULL DEFAULT 0,
  `user_address` VARCHAR(100) NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_user_balance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_user_balance` (
  `uid` INT NOT NULL,
  `user_balance` DOUBLE NOT NULL DEFAULT 0,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_user_coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_user_coupon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` INT NOT NULL,
  `user_title` VARCHAR(45) NULL,
  `user_content` VARCHAR(1000) NULL,
  `user_type` VARCHAR(45) NULL,
  `user_full` DOUBLE NULL,
  `user_subtract` DOUBLE NULL,
  `user_status` INT NOT NULL DEFAULT 0,
  `user_expiredtime` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_user_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_user_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` INT NOT NULL,
  `user_address` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_user_balance_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_user_balance_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` INT NOT NULL,
  `user_old_balance` DOUBLE NOT NULL,
  `user_amount` DOUBLE NOT NULL,
  `user_new_balance` DOUBLE NOT NULL,
  `user_type` VARCHAR(45) NULL,
  `user_number` VARCHAR(45) NOT NULL,
  `user_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_user_preference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_user_preference` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` INT NOT NULL,
  `user_goodstype` VARCHAR(45) NULL,
  `user_goods` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_deliveryuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_deliveryuser` (
  `did` INT NOT NULL,
  `delivery_username` VARCHAR(45) NULL,
  `delivery_password` VARCHAR(45) NULL,
  `delivery_date` DATETIME NULL,
  PRIMARY KEY (`did`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_delivery_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_delivery_info` (
  `did` INT NOT NULL,
  `delivery_photo` VARCHAR(100) NULL,
  `delivery_name` VARCHAR(45) NOT NULL,
  `delivery_card` VARCHAR(45) NOT NULL,
  `delivery_gender` INT NOT NULL DEFAULT 0,
  `delivery_phone` VARCHAR(45) NOT NULL,
  `delivery_address` VARCHAR(100) NULL,
  `delivery_point` INT NULL DEFAULT 0,
  `delivery_level` VARCHAR(45) NULL,
  PRIMARY KEY (`did`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_delivery_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_delivery_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `did` INT NOT NULL,
  `delivery_address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_delivery_balance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_delivery_balance` (
  `did` INT NOT NULL,
  `delivery_balance` DOUBLE NOT NULL DEFAULT 0,
  PRIMARY KEY (`did`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_delivery_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_delivery_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `did` INT NOT NULL,
  `delivery_old_balance` DOUBLE NOT NULL,
  `delivery_amount` DOUBLE NOT NULL,
  `delivery_new_balance` DOUBLE NOT NULL,
  `delivery_type` VARCHAR(45) NULL,
  `delivery_number` VARCHAR(45) NOT NULL,
  `delivery_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_order` (
  `orderid` VARCHAR(45) NOT NULL,
  `uid` INT NOT NULL,
  `did` INT NULL,
  `business_name` VARCHAR(45) NULL,
  `business_address` VARCHAR(100) NULL,
  `order_goods` VARCHAR(200) NOT NULL,
  `order_remark` VARCHAR(45) NULL,
  `order_price` DOUBLE NULL,
  `order_fee` DOUBLE NULL,
  `order_tip` DOUBLE NULL,
  `order_type` INT NOT NULL DEFAULT 0,
  `order_recv_address` INT NOT NULL,
  `order_phone` VARCHAR(45) NOT NULL,
  `order_speed` VARCHAR(45) NOT NULL,
  `order_sendtime` DATETIME NULL,
  `order_recv_longitude` VARCHAR(45) NOT NULL,
  `order_recv_latitude` VARCHAR(45) NOT NULL,
  `order_time` DATETIME NULL,
  PRIMARY KEY (`orderid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_order_status` (
  `orderid` VARCHAR(45) NOT NULL,
  `uid` INT NOT NULL,
  `did` INT NULL,
  `order_is_submit` INT NULL DEFAULT 0,
  `order_is_pay` INT NULL DEFAULT 0,
  `order_is_orders` INT NULL DEFAULT 0,
  `order_is_send` INT NULL DEFAULT 0,
  `order_is_finish` INT NULL DEFAULT 0,
  `order_orders_time` DATETIME NULL,
  `order_finish_time` DATETIME NULL,
  PRIMARY KEY (`orderid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_order_pay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_order_pay` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` INT NOT NULL,
  `orderid` VARCHAR(45) NOT NULL,
  `order_price` DOUBLE NOT NULL,
  `order_tip` DOUBLE NULL,
  `order_subtract` DOUBLE NULL,
  `order_actual_price` DOUBLE NULL,
  `order_type` VARCHAR(45) NULL,
  `order_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_delivery_distance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_delivery_distance` (
  `did` INT NOT NULL,
  `send_distance` DOUBLE NOT NULL DEFAULT -1,
  `delivery_distance` DOUBLE NOT NULL DEFAULT -1,
  `view_order_distance` DOUBLE NOT NULL DEFAULT -1,
  PRIMARY KEY (`did`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_push_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_push_info` (
  `pid` INT NOT NULL AUTO_INCREMENT,
  `push_title` VARCHAR(100) NULL,
  `push_content` VARCHAR(1000) NULL,
  `push_photo` VARCHAR(100) NULL,
  `push_status` INT NOT NULL DEFAULT 0,
  `push_time` DATETIME NULL,
  PRIMARY KEY (`pid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_admin` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `admin_username` VARCHAR(45) NOT NULL,
  `admin_password` VARCHAR(45) NOT NULL,
  `admin_time` VARCHAR(45) NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Running_Bussiness`.`run_admin_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Running_Bussiness`.`run_admin_info` (
  `admin_id` INT NOT NULL,
  `admin_name` VARCHAR(45) NULL,
  `admin_phone` VARCHAR(45) NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
